var lang_en = {
	find_pare: 'Game «Find a pare»',
	begin: 'Next Step',
	Back: 'Back',
	group_back: 'Back',
	group_lookup: 'Groups',
	about_game: 'About',
	levels_count: 'Copy\'s Levels',
	number_1: 'x1',
	number_2: 'x2',
	number_3: 'x3',
	number_4: 'x4',
	number_5: 'x5',
	field_size: 'Field size',
	about: 'Images from sites, i hope they agree:',
	you_win_points: 'Your points',
	quick_start: 'Start!',
	my_result: 'My result',
	go_to_site: 'Go to site',
	watch_video: 'watch video',

	groups: 'Groups',
	avatars_level: 'Group level',
	in_game: 'Find a pare',
	winner: 'Winner!',


	group_colors: 'Colors',

	white: 'White',
	red: 'Red',
	yellow: 'Yellow',
	green: 'Green',
	blue: 'Blue',
	black: 'Black',

	aqua: 'Aqua',
	fuchsia: 'Fuchsia',
	gray: 'Gray',
	lime: 'Lime',
	maroon: 'Maroon',
	navy: 'Navy',
	olive: 'Olive',
	purple: 'Purple',
	silver: 'Silver',
	teal: 'Teal',


	group_numbers: 'Math',

	world_number_0: 'Zero',
	world_number_1: 'One',
	world_number_2: 'Two',
	world_number_3: 'Three',
	world_number_4: 'Four',
	world_number_5: 'Five',
	world_number_6: 'Six',
	world_number_7: 'Seven',
	world_number_8: 'Eight',
	world_number_9: 'Nine',

	world_number_plus: 'plus',
	world_number_minus: 'minus',
	world_number_division: 'Division',
	world_number_multiply: 'Multiply',
	world_number_equality: 'Equality',


	group_fairies: 'Fairies',
	fairies_site: 'www.disney.com/fairies/',
	fairies_site_video: 'www.disney.com/fairies/#/videos/',

	fairies_din_din: 'Din-Din',
	fairies_fauna: 'Fauna',
	fairies_iridessa: 'Iridessa',
	fairies_nezabudka: 'Nezabudka',
	fairies_rozetta: 'Rozetta',
	fairies_serebryanka: 'Serebryanka',
	fairies_vidiya: 'Vidiya',
	fairies_zarina: 'Zarina',


	group_jake: 'Jake',
	jake_site: 'jake.disney.com/',
	jake_site_video: '',

	jake_baki: 'Baki',
	jake_dzheyk: 'Dzheyk',
	jake_izzi: 'Izzi',
	jake_kabbi: 'Kabbi',
	jake_kapitan_kryuk: 'Kapitan Kryuk',
	jake_mister_smi: 'Mister Smi',
	jake_skalli: 'Skalli',
	jake_tik_tak: 'Tik-Tak',


	group_princess: 'Princess',
	princess_site: 'www.disney.com/princess/',
	princess_site_video: 'www.disney.com/princess/#/videos/',

	princess_ariel: 'Ariel',
	princess_avrora: 'Avrora',
	princess_bell: 'Bell',
	princess_belosnezhka: 'Belosnezhka',
	princess_merida: 'Merida',
	princess_mulan: 'Mulan',
	princess_pokahontas: 'Pokahontas',
	princess_rapuntsel: 'Rapuntsel',
	princess_tiana: 'Tiana',
	princess_zhasmin: 'Zhasmin',
	princess_zolushka: 'Zolushka',


	group_winnie: 'Winnie',
	winnie_site: 'www.disney.com/pooh/',
	winnie_site_video: 'www.disney.com/pooh/videos/',

	winnie_filin: 'Filin',
	winnie_hryunya: 'Hryunya',
	winnie_kenga_i_ru: 'Kenga i Ru',
	winnie_kristofer_robin: 'Kristofer Robin',
	winnie_krolik: 'Krolik',
	winnie_medvezhonok_vinni: 'Medvezhonok Vinni',
	winnie_tigrulya: 'Tigrulya',
	winnie_ushastik: 'Ushastik',


	group_smeshariki: 'Smeshariki',
	smeshariki_site: '',
	smeshariki_site_video: '',

	smeshariki_Barash: 'Barash',
	smeshariki_KarKarych: 'KarKarych',
	smeshariki_Kopatych: 'Kopatych',
	smeshariki_Krosh: 'Krosh',
	smeshariki_Losyash: 'Losyash',
	smeshariki_Nysha: 'Nysha',
	smeshariki_Pin: 'Pin',
	smeshariki_Sovuniya: 'Sovuniya',
	smeshariki_Yozh: 'Yozh',


	group_barboskiny: 'Pooches',
	barboskiny_site: 'thepooches.tv/',
	barboskiny_site_video: 'thepooches.tv/episodes/',

	Barboskiny_dryjok: 	'Max',
	Barboskiny_gena: 	'Alex',
	Barboskiny_liza: 	'Liza',
	Barboskiny_malish: 	'Kid',
	Barboskiny_rosa: 	'Rosie',


	group_fixiki: 'Fixiki',
	fixiki_site: '',
	fixiki_site_video: '',

	Fixiki_dedus: 			'Grand Father',
	Fixiki_dimdimych: 		'Dim-Dimych',
	Fixiki_fire: 			'Fire',
	Fixiki_juchka: 			'Guchka',
	Fixiki_kusachka: 		'Kusachka',
	Fixiki_masya: 			'Mamy',
	Fixiki_nolik: 			'Zero',
	Fixiki_papus: 			'Papy',
	Fixiki_prof_chudakov: 	'Phd. Lucky',
	Fixiki_shpulya: 		'Shpylya',
	Fixiki_simka: 			'Simka',
	Fixiki_verta: 			'Vetra',
	Fixiki_ygrek: 			'Ygrek',


	group_luntik: 'Luntik',
	luntik_site: '',
	luntik_site_video: '',

	Luntik_baba_kapa: 			'Kapa',
	Luntik_kuzya: 				'Kuzya',
	Luntik_luntik: 				'Luntik',
	Luntik_mila: 				'Mila',
	Luntik_pchelonok: 			'Pchelenok',
	Luntik_sher: 				'Mr. Sher',
	Luntik_vupsen_i_pupsen: 	'Vupsen &&nbsp;Pupsen',


	group_winx: 'Winx',
	winx_site: 'www.winxclub.com/en/',
	winx_site_video: 'www.winxclub.com/en/videos/',

	Winx_aisha: 	'Aisha',
	Winx_bloom: 	'Bloom',
	Winx_flora: 	'Flora',
	Winx_musa: 		'Musa',
	Winx_stella: 	'Stella',
	Winx_tecna: 	'Tecna',


	group_mashabear: 'Masha &&nbsp;Bear',
	mashabear_site: 'mashabear.com/',
	mashabear_site_video: 'mashabear.com/video/',

	Mashabear_bear: 		'Bear',
	Mashabear_bear_2: 		'Bear',
	Mashabear_bear_3: 		'Mis. Bear',
	Mashabear_hedgehog: 	'Hedgehog',
	Mashabear_masha: 		'Masha',
	Mashabear_panda: 		'Panda',
	Mashabear_penguin: 		'Penguin',
	Mashabear_rabbit: 		'Rabbit',
	Mashabear_squirrel: 	'Squirrel',
	Mashabear_tiger: 		'Tiger',
	Mashabear_wolf: 		'Heather wolf',
	Mashabear_wolf_2: 		'Stupid wolf',


	group_alisamovie: 'Alisa movie',
	alisamovie_site: '',
	alisamovie_site_video: '',

	Alisamovie_alisa: 	'Alisa',
	Alisamovie_arik: 	'Arik',
	Alisamovie_leha: 	'Leha',
	Alisamovie_masha: 	'Masha',
	Alisamovie_natasha: 'Natasha',
	Alisamovie_pupper: 	'Pupper',
	Alisamovie_per1: 	'Gromozeka',
	Alisamovie_per2: 	'Alisa\'s mother',
	Alisamovie_per3: 	'Polya',
	Alisamovie_per4: 	'Phd. Sapojnikov',
	Alisamovie_per5: 	'Alisa\'s father',
	Alisamovie_per6: 	'Vasiliy Petrovich',


	group_bogatirya_3: '3&nbsp;Hero',
	bogatirya_3_site: '',
	bogatirya_3_site_video: '',

	Bogatirya_3_alena: 'Alena',
	Bogatirya_3_alesha: 'Alesha Popovich',
	Bogatirya_3_babka: 'grand ma',
	Bogatirya_3_beket: 'Beket',
	Bogatirya_3_burushka: 'Burushka',
	Bogatirya_3_dobrinya: 'Dobrynya Nikitish',
	Bogatirya_3_elisey: 'Elisey',
	Bogatirya_3_gorinich: 'zmey-Gorinych',
	Bogatirya_3_ilya: 'Ilya Muromets',
	Bogatirya_3_ivan: 'Ivan',
	Bogatirya_3_knyaz: 'Kiev\'s Prince',
	Bogatirya_3_kolivan: 'Lokyvan',
	Bogatirya_3_kupets: 'Merchant',
	Bogatirya_3_lyubava: 'Lubava',
	Bogatirya_3_moisey: 'Moisey',
	Bogatirya_3_nastasya: 'Nastasiya',
	Bogatirya_3_rabotorg: 'Slaver',
	Bogatirya_3_shamahan: 'Shamakhan\'s queen',
	Bogatirya_3_slon: 'Elefant',
	Bogatirya_3_solovei: 'Solovey rogue',
	Bogatirya_3_svyatogor: 'Svyatogor',
	Bogatirya_3_tihon: 'grand pa Tikhon',
	Bogatirya_3_tsar: 'King',
	Bogatirya_3_tugarin: 'Tugarin-zmey',
	Bogatirya_3_vasilevs: 'Vasilevs',
	Bogatirya_3_vasilisa: 'Valilisa',
	Bogatirya_3_vasya: 'Vasya',
	Bogatirya_3_volk: 'Vulf',
	Bogatirya_3_yaga: 'baba-Yaga',
	Bogatirya_3_yuly: 'Yaliy',
	Bogatirya_3_zabava: 'Zabava'

};
