var lang_ru = {
	find_pare: 'Игра «Найди пару»',
	begin: 'Далее',
	Back: 'Назад',
	group_back: 'Назад',
	group_lookup: 'Наборы',
	about_game: 'Об игре',
	levels_count: 'Количество копий',
	number_1: 'x1',
	number_2: 'x2',
	number_3: 'x3',
	number_4: 'x4',
	number_5: 'x5',
	field_size: 'Размер поля',
	about: 'Картинки с&nbsp;сайтов, надеюсь, они не против:',
	you_win_points: 'Ваши баллы за игру',
	quick_start: 'Начали!',
	my_result: 'Мой результат',
	go_to_site: 'Перейти на сайт',
	watch_video: 'смотреть видео',

	groups: 'Наборы',
	avatars_level: 'Сложность набора',
	in_game: 'Найди пару',
	winner: 'Победа!',


	group_colors: 'Цвета',

	white: 		'Белый',
	red: 		'Красный',
	yellow: 	'Желтый',
	green: 		'Зелёный',
	blue: 		'Синий',
	black: 		'Черный',

	aqua: 		'Морская волна',
	fuchsia: 	'Розовый',
	gray: 		'Серый',
	lime: 		'Ярко-зелёный',
	maroon: 	'Коричневый',
	navy: 		'Тёмно-синий',
	olive: 		'Тёмно-зелёный',
	purple: 	'Фиолетовый',
	silver: 	'Светло-серый',
	teal: 		'Серо-зелёный',


	group_numbers: 'Математика',

	world_number_0: 'Ноль',
	world_number_1: 'Один',
	world_number_2: 'Два',
	world_number_3: 'Три',
	world_number_4: 'Четыре',
	world_number_5: 'Пять',
	world_number_6: 'Шесть',
	world_number_7: 'Семь',
	world_number_8: 'Восемь',
	world_number_9: 'Девять',

	world_number_plus: 'Плюс',
	world_number_minus: 'Минус',
	world_number_division: 'Разделить',
	world_number_multiply: 'Умножить',
	world_number_equality: 'Равно',


	group_fairies: 'Феи',
	fairies_site: 'www.disney.ru/fairies/',
	fairies_site_video: 'www.disney.ru/fairies/#/videos/',

	fairies_din_din: 		'Динь-Динь',
	fairies_fauna: 			'Фауна',
	fairies_iridessa: 		'Иридесса',
	fairies_nezabudka: 		'Незабудка',
	fairies_rozetta: 		'Розетта',
	fairies_serebryanka: 	'Серебрянка',
	fairies_vidiya: 		'Видия',
	fairies_zarina: 		'Зарина',


	group_jake: 'Джейк',
	jake_site: 'jake.disney.ru/',
	jake_site_video: '',

	jake_baki: 				'Баки',
	jake_dzheyk: 			'Джейк',
	jake_izzi: 				'Иззи',
	jake_kabbi: 			'Кабби',
	jake_kapitan_kryuk: 	'Капитан Крюк',
	jake_mister_smi: 		'Мистер Сми',
	jake_skalli: 			'Скалли',
	jake_tik_tak: 			'Тик-Так',


	group_princess: 'Принцессы',
	princess_site: 'www.disney.ru/princess/',
	princess_site_video: 'www.disney.ru/princess/#/videos/',

	princess_ariel: 		'Ариэль',
	princess_avrora: 		'Аврора',
	princess_bell: 			'Бель',
	princess_belosnezhka: 	'Белоснежка',
	princess_merida: 		'Мерида',
	princess_mulan: 		'Мулан',
	princess_pokahontas: 	'Покахонтас',
	princess_rapuntsel: 	'Рапунцель',
	princess_tiana: 		'Тиана',
	princess_zhasmin: 		'Жасмин',
	princess_zolushka: 		'Золушка',


	group_winnie: 'Винни',
	winnie_site: 'www.disney.ru/pooh/',
	winnie_site_video: 'www.disney.ru/pooh/videos/',

	winnie_filin: 				'Филинн',
	winnie_hryunya: 			'Хрюня',
	winnie_kenga_i_ru: 			'Кенга и Ру',
	winnie_kristofer_robin: 	'Кристофер Робин',
	winnie_krolik: 				'Кролик',
	winnie_medvezhonok_vinni: 	'Медв. Винни',
	winnie_tigrulya: 			'Тигруля',
	winnie_ushastik: 			'Ушастик',


	group_smeshariki: 'Смешарики',
	smeshariki_site: 'www.smeshariki.ru/',
	smeshariki_site_video: 'www.smeshariki.ru/mult/',

	smeshariki_Barash: 		'Бараш',
	smeshariki_KarKarych: 	'Кар-Карыч',
	smeshariki_Kopatych: 	'Копатыч',
	smeshariki_Krosh: 		'Крош',
	smeshariki_Losyash: 	'Лосяш',
	smeshariki_Nysha: 		'Нюша',
	smeshariki_Pin: 		'Пин',
	smeshariki_Sovuniya: 	'Совуня',
	smeshariki_Yozh: 		'Ёж',


	group_barboskiny: 'Барбоскины',
	barboskiny_site: 'barboskiny.ru/',
	barboskiny_site_video: 'barboskiny.ru/series/',

	Barboskiny_dryjok: 	'Дружок',
	Barboskiny_gena: 	'Гена',
	Barboskiny_liza: 	'Лиза',
	Barboskiny_malish: 	'Малыш',
	Barboskiny_rosa: 	'Роза',


	group_fixiki: 'Фиксики',
	fixiki_site: 'fixiki.ru/',
	fixiki_site_video: 'fixiki.ru/watch/',

	Fixiki_dedus: 			'Дедус',
	Fixiki_dimdimych: 		'Дим-Димыч',
	Fixiki_fire: 			'Фаер',
	Fixiki_juchka: 			'Жучка',
	Fixiki_kusachka: 		'Кусачка',
	Fixiki_masya: 			'Мася',
	Fixiki_nolik: 			'Нолик',
	Fixiki_papus: 			'Папус',
	Fixiki_prof_chudakov: 	'Проф. Чудаков',
	Fixiki_shpulya: 		'Шпуля',
	Fixiki_simka: 			'Симка',
	Fixiki_verta: 			'Верта',
	Fixiki_ygrek: 			'Игрек',


	group_luntik: 'Лунтик',
	luntik_site: 'luntik.ru/',
	luntik_site_video: 'luntik.ru/cartoons/',

	Luntik_baba_kapa: 			'Баба-Капа',
	Luntik_kuzya: 				'Кузя',
	Luntik_luntik: 				'Лунтик',
	Luntik_mila: 				'Мила',
	Luntik_pchelonok: 			'Пчелёнок',
	Luntik_sher: 				'Шер',
	Luntik_vupsen_i_pupsen: 	'Вупсень и&nbsp;Пупсень',


	group_winx: 'Винкс',
	winx_site: 'www.winxclub.com/ru/',
	winx_site_video: 'www.winxclub.com/ru/videos/',

	Winx_aisha: 	'Лейла',
	Winx_bloom: 	'Блум',
	Winx_flora: 	'Фрола',
	Winx_musa: 		'Муза',
	Winx_stella: 	'Стелла',
	Winx_tecna: 	'Текна',


	group_mashabear: 'Маша и&nbsp;Медведь',
	mashabear_site: 'mashabear.ru/',
	mashabear_site_video: 'mashabear.ru/video/',

	Mashabear_bear: 		'Медведь',
	Mashabear_bear_2: 		'Медведь гим.',
	Mashabear_bear_3: 		'Медведица',
	Mashabear_hedgehog: 	'Ёжик',
	Mashabear_masha: 		'Маша',
	Mashabear_panda: 		'Панда',
	Mashabear_penguin: 		'Пингвин',
	Mashabear_rabbit: 		'Заяц',
	Mashabear_squirrel: 	'Белка',
	Mashabear_tiger: 		'Тигр',
	Mashabear_wolf: 		'Хитрый волк',
	Mashabear_wolf_2: 		'Глупый волк',


	group_alisamovie: 'Алиса спешит',
	alisamovie_site: 'alisamovie.ru/',
	alisamovie_site_video: 'alisamovie.ru/episodes/',

	Alisamovie_alisa: 	'Алиса',
	Alisamovie_arik: 	'Арик',
	Alisamovie_leha: 	'Лёха',
	Alisamovie_masha: 	'Маша',
	Alisamovie_natasha: 'Наташа',
	Alisamovie_pupper: 	'Пуппер',
	Alisamovie_per1: 	'Громозека',
	Alisamovie_per2: 	'Мама Алисы',
	Alisamovie_per3: 	'Поля',
	Alisamovie_per4: 	'акад. Сапожков',
	Alisamovie_per5: 	'Папа Алисы',
	Alisamovie_per6: 	'Василий Петрович',


	group_bogatirya_3: '3&nbsp;Богатыря',
	bogatirya_3_site: '3bogatirya.ru/',
	bogatirya_3_site_video: '3bogatirya.ru/category/video-tsitatyi/',

	Bogatirya_3_alena: 'Алёна',
	Bogatirya_3_alesha: 'Алёша Попович',
	Bogatirya_3_babka: 'Бабушка',
	Bogatirya_3_beket: 'Бекет',
	Bogatirya_3_burushka: 'Бурушка',
	Bogatirya_3_dobrinya: 'Добрыня Никитич',
	Bogatirya_3_elisey: 'Елисей',
	Bogatirya_3_gorinich: 'змей-Горыныч',
	Bogatirya_3_ilya: 'Илья Муромец',
	Bogatirya_3_ivan: 'Иван',
	Bogatirya_3_knyaz: 'Князь киевский',
	Bogatirya_3_kolivan: 'Колыван',
	Bogatirya_3_kupets: 'Купец',
	Bogatirya_3_lyubava: 'Любава',
	Bogatirya_3_moisey: 'Моисей',
	Bogatirya_3_nastasya: 'Настасья',
	Bogatirya_3_rabotorg: 'Работорговец',
	Bogatirya_3_shamahan: 'Шамаханская цар.',
	Bogatirya_3_slon: 'Слон',
	Bogatirya_3_solovei: 'Соловей-разб.',
	Bogatirya_3_svyatogor: 'Святогор',
	Bogatirya_3_tihon: 'дед Тихон',
	Bogatirya_3_tsar: 'Царь',
	Bogatirya_3_tugarin: 'Тугарин-змей',
	Bogatirya_3_vasilevs: 'Василевс',
	Bogatirya_3_vasilisa: 'Василиса',
	Bogatirya_3_vasya: 'Вася',
	Bogatirya_3_volk: 'Волк',
	Bogatirya_3_yaga: 'баба-Яга',
	Bogatirya_3_yuly: 'Юлий',
	Bogatirya_3_zabava: 'Забава'

};
